### ISSUE TITLE
Remove COLOUR alias in EntityMetadataProperties for consistency

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/BedrockProtocol#3]
## Description
POTION_COLOR and COLOR_2 also have no alias. To prevent a mix of COLOR and COLOUR in PMMP, it is advised to remove the BE variant instead

This might break some plugins that use the COLOUR constant.

## Justification
dylan agreed🙃

**Comment by dktapps** [comment]
For posterity: While I dislike American English (AE), it's preferable to always consistently use AE rather than mix AE and BE, for the sake of consistency and guessability. Since switching to BE would unnecessarily break a bunch of stuff (PM and its libraries already mostly use AE), we should stick consistently with AE.
